const ERROR_CODES = {
  INVALID_FILE: 'INVALID_FILE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VIDEO_NOT_FOUND: 'VIDEO_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  PROCESSING_FAILED: 'PROCESSING_FAILED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  STREAM_NOT_ALLOWED: 'STREAM_NOT_ALLOWED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  INVALID_RANGE: 'INVALID_RANGE',
  SERVER_ERROR: 'SERVER_ERROR',
  INVALID_PAGINATION: 'INVALID_PAGINATION',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
};

module.exports = { ERROR_CODES };
