const VIDEO_STATUS = {
  UPLOADED: 'UPLOADED',
  VALIDATING: 'VALIDATING',
  PROCESSING: 'PROCESSING',
  ANALYZED: 'ANALYZED',
  READY: 'READY',
  FAILED: 'FAILED',
};

const SENSITIVITY = {
  SAFE: 'SAFE',
  FLAGGED: 'FLAGGED',
};

const ALLOWED_TRANSITIONS = {
  [VIDEO_STATUS.UPLOADED]: [VIDEO_STATUS.VALIDATING, VIDEO_STATUS.FAILED],
  [VIDEO_STATUS.VALIDATING]: [VIDEO_STATUS.PROCESSING, VIDEO_STATUS.FAILED],
  [VIDEO_STATUS.PROCESSING]: [VIDEO_STATUS.ANALYZED, VIDEO_STATUS.FAILED],
  [VIDEO_STATUS.ANALYZED]: [VIDEO_STATUS.READY, VIDEO_STATUS.FAILED],
  [VIDEO_STATUS.READY]: [],
  [VIDEO_STATUS.FAILED]: [],
};

module.exports = { VIDEO_STATUS, SENSITIVITY, ALLOWED_TRANSITIONS };
